In [13]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import average_precision_score
from sklearn.metrics import roc_auc_score

from tensorflow.keras.models import load_model
import autokeras as ak
import numpy as np
import os

# ds_arrays_path = '/content/drive/MyDrive/TG/dataset_arraysTRAINING'
models_path = '/Volumes/SAMSUNG/Igor/TG/training'
ds_arrays_path = '/Users/igorbeduin/Google Drive (beduinigor@gmail.com)/TG/dataset_arraysTRAINING'

optimizers = ['sgd', 'Adam']
ds_train = ['raw', 'augmented']

n_fold = 5

for opt in optimizers:
    opt_path = os.path.join(models_path, opt)
    for ds in ds_train:
        ds_path = os.path.join(opt_path, ds)
        for i in range(1, n_fold + 1):
            fold_path = os.path.join(ds_path, 'models', f'fold_{i}')
            files_list = os.listdir(fold_path)
            for f in files_list:
                if 'model' in f:
                    
                    print(f'Opt: {opt}, DS: {ds}, filename: {f}')

                    model_path = os.path.join(fold_path, f)
                    model = load_model(model_path)

                    X_test = np.load(os.path.join(ds_arrays_path,'x_test_data.npy'))
                    y_test = np.load(os.path.join(ds_arrays_path,'y_test_data.npy'))

                    predictions = model.predict(x=X_test)
                    num_predictions = np.argmax(predictions, axis=-1)
                    print(classification_report(y_test, num_predictions))
                    print(confusion_matrix(y_test, num_predictions))
                    # print(average_precision_score(y_test, num_predictions))

Opt: sgd, DS: raw, filename: model_fold_1.h5
              precision    recall  f1-score   support

           0       0.00      0.00      0.00      1761
           1       0.00      0.00      0.00      1216
           2       0.03      1.00      0.06       103

    accuracy                           0.03      3080
   macro avg       0.01      0.33      0.02      3080
weighted avg       0.00      0.03      0.00      3080

[[   0    0 1761]
 [   0    0 1216]
 [   0    0  103]]
Opt: sgd, DS: raw, filename: model_fold_2.h5
              precision    recall  f1-score   support

           0       0.00      0.00      0.00      1761
           1       0.00      0.00      0.00      1216
           2       0.03      1.00      0.06       103

    accuracy                           0.03      3080
   macro avg       0.01      0.33      0.02      3080
weighted avg       0.00      0.03      0.00      3080

[[   0    0 1761]
 [   0    0 1216]
 [   0    0  103]]
Opt: sgd, DS: raw, filename: model_fol

KeyboardInterrupt: 